# Generated by Django 4.2.1 on 2023-09-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabRentalProviders',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('services_offered', models.TextField()),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=3)),
                ('images', models.ImageField(upload_to='provider_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='destination_images/')),
            ],
        ),
        migrations.CreateModel(
            name='GuideProviders',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('services_offered', models.TextField()),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=3)),
                ('images', models.ImageField(upload_to='provider_images/')),
            ],
        ),
        migrations.CreateModel(
            name='HotelProviders',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('services_offered', models.TextField()),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=3)),
                ('images', models.ImageField(upload_to='provider_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cab_rental_provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('guide_provider_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_rating', models.IntegerField()),
                ('cab_rental_rating', models.IntegerField()),
                ('guide_rating', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('max_participants', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.destinations')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='profile_images/')),
                ('bio', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('guide', 'Guide'), ('hotel_manager', 'Hotel Manager'), ('cab_rental', 'Cab Rental')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='trips',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.userprofile'),
        ),
        migrations.AddField(
            model_name='tripratings',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.trips'),
        ),
        migrations.AddField(
            model_name='tripratings',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.userprofile'),
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.userprofile'),
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.trips'),
        ),
    ]
